# Основные параметры обнаружения препятствий
obstacle_range: 2.5                 # МЕНЯТЬ: дальность обнаружения препятствий
raytrace_range: 3.0                 # МЕНЯТЬ: дальность очистки карты
footprint: [[-0.25, -0.25], [-0.25, 0.25], [0.25, 0.25], [0.25, -0.25]]  # МЕНЯТЬ: форма робота
inflation_radius: 0.02              # МЕНЯТЬ: буферная зона вокруг препятствий

# Параметры стоимости
map_type: costmap
unknown_cost_value: -1
lethal_cost_threshold: 100
inscribed_inflated_radius: 0.325
cost_scaling_factor: 10.0

# Разрешение
resolution: 0.05

# Источники данных
observation_sources: scan
scan: 
  sensor_frame: base_scan
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true