mobile_base_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: 'wheel_left_link'
  right_wheel: 'wheel_right_link'
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
  
  wheel_separation: 0.160
  wheel_radius: 0.033

  wheel_separation_multiplier: 1.0
  left_wheel_radius_multiplier: 1.0
  right_wheel_radius_multiplier: 1.0

  publish_rate: 50.0

joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50.0