# Основные фреймы
base_frame: base_footprint
odom_frame: odom
map_frame: map

# Параметры карты
map_update_interval: 2.0
maxUrange: 3.5
particles: 30
delta: 0.05

# Параметры обновления
linearUpdate: 0.5
angularUpdate: 0.436
temporalUpdate: -1.0

# Размеры карты
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0

# Параметры лазера
sigma: 0.05
kernelSize: 1
lstep: 0.05
astep: 0.05
iterations: 5
lsigma: 0.075
ogain: 3.0
lskip: 0

# Параметры движения
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2

# Дополнительные параметры
minimumScore: 50.0
resampleThreshold: 0.5
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005