local_costmap:
  global_frame: odom                # Система координат
  robot_base_frame: base_footprint  # База робота
  update_frequency: 10.0            # Частота обновления (Гц)
  publish_frequency: 10.0           # Частота публикации
  transform_tolerance: 0.5          # Толерантность трансформ
  static_map: false                 # Не использовать статическую карту
  rolling_window: true              "Окно", движущееся с роботом
  width: 3.0                        # Ширина окна (метры)
  height: 3.0                       # Высота окна
  resolution: 0.05                  # Разрешение (метры/пиксель)